#!/bin/bash

set -Eemo pipefail

docker-entrypoint.sh postgres > /dev/null 2>&1 &
LOCKFILE=$PGDATA/postmaster.pid

RETRIES=5

until psql -U postgres -d postgres -c 'select 1' > /dev/null 2>&1 || [ $RETRIES -eq 0 ]; do
    RETRIES=`expr $RETRIES - 1`
    echo "Waiting for postgres server, $RETRIES remaining attempts..."
    sleep 1
done

HAS_DB_ROWS=$(psql -U postgres -c "SELECT 1 AS result FROM pg_database WHERE datname='message_store'" | wc -l)
if [ $HAS_DB_ROWS -lt 5 ]
then
    su -c evt-pg-create-db postgres
fi

fg %1

exec "$@"
